'use client';

import { Button } from '@/components/ui/button';
import { motion } from 'framer-motion';
import { Sparkles } from 'lucide-react';
import Link from 'next/link';
import Image from 'next/image';
import {
	FaDiscord,
	FaLinkedin,
	FaTelegram,
	FaXTwitter,
	FaYoutube,
} from 'react-icons/fa6';
import {
	Accordion,
	AccordionContent,
	AccordionItem,
	AccordionTrigger,
} from '@/components/ui/accordion';
import { useState } from 'react';
import Connect from '@/components/ui/Connect';

export default function Home() {
	const features = [
		{
			title: 'Token supply',
			description:
				'24 billion NIGHT tokens minted on Cardano, which are mirrored on the Midnight network.',
		},
		{
			title: 'Disinflationary',
			description:
				'The expansion of the circulating supply via block rewards slows down over time, until the total supply is circulating and no more inflation occurs',
		},
		{
			title: 'Non-expendable',
			description:
				'NIGHT is not expendable to execute transactions, nor destroyed/burned during the exercise of its functions.',
		},
		{
			title: 'Multi-chain',
			description:
				'In contrast with wrapped token representations, NIGHT exists natively and maintains the same properties and rights both on Cardano and on Midnight',
		},
	];
	const features2 = [
		{
			title: 'Shielded',
			description:
				'DUST allows for transactions to take place without exposing metadata.',
		},
		{
			title: 'Consumable',
			description:
				'DUST is consumed when used – meaning it is destroyed and does not cycle back into circulation.',
		},
		{
			title: 'Renewable',
			description:
				'DUST is continually generated by NIGHT balances in perpetuity.',
		},
		{
			title: 'Decaying',
			description:
				'A DUST balance decays when disassociated from the NIGHT address that generates it, meaning it cannot act as a store of value',
		},
		{
			title: 'Non-transferable',
			description:
				'DUST cannot be transferred between addresses – insulating it from volatility and strengthening its sole utility.',
		},
	];
	const [open, setOpen] = useState(false);
	return (
		<>
			<Connect
				open={open}
				onClose={() => setOpen(false)}
			/>
			<div className='min-h-screen bg-white text-black '>
				{/* Navigation */}
				<nav className='fixed top-0 w-full z-50 glass-effect '>
					<div className='border-b border-gray-400 mx-auto px-4 sm:px-6 lg:px-10 '>
						<div className='flex justify-between items-center h-20 '>
							<div className='flex items-center gap-x-10'>
								<motion.div
									initial={{ opacity: 0, x: -20 }}
									animate={{ opacity: 1, x: 0 }}
									className='flex items-end space-x-2'
								>
									<Image
										src='/logo.svg'
										alt='logo'
										width={24}
										height={24}
									/>
									<span className='text-lg font-bold text-[var(--primary-color)]'>
										Midnight
									</span>
								</motion.div>
								<div className='md:flex items-center gap-x-2 lg:gap-x-4 uppercase hidden '>
									<a
										className='text-sm lg:text-base'
										href='/'
									>
										Home
									</a>
									<a
										className='text-sm lg:text-base'
										href='https://www.midnight.gd/how-to-get-night'
									>
										How to get night
									</a>
									<a
										className='text-sm lg:text-base'
										href='https://www.midnight.gd/tokenomics'
									>
										Tokenomics
									</a>
									<a
										className='text-sm lg:text-base'
										href='https://www.midnight.gd/news'
									>
										news
									</a>
									<a href='https://www.midnight.gd/faqs'>
										faqs
									</a>
								</div>
							</div>

							<motion.div
								initial={{ opacity: 0, x: 20 }}
								animate={{ opacity: 1, x: 0 }}
								className='flex md:space-x-8 space-x-4 items-center'
							>
								<Button
									className='bg-[var(--primary-color)] h-12 uppercase text-white py-2 hover:bg-blue-800'
									onClick={() => setOpen(true)}
								>
									<Link href='/'>sign up for updates</Link>
								</Button>
								<div
									className='space-y-1 lg:hidden'
									onClick={() => setOpen(true)}
								>
									<span className='h-1 w-7 bg-gray-500 block rounded-full'></span>
									<span className='h-1 w-7 bg-gray-500 block rounded-full'></span>
								</div>
							</motion.div>
						</div>
					</div>
					<div className='overflow-x-hidden'>
						<div className='h-12 border-b border-gray-400 px-10 flex items-center gap-x-10 min-w-[1000px] overflow-x-scroll scrollbar-hide'>
							<p>JUMP TO:</p>
							<div className='uppercase flex items-center gap-x-6'>
								<a
									className='text-sm lg:text-base font-mono'
									href='#distribution'
								>
									distribution
								</a>
								<a
									className='text-sm lg:text-base font-mono'
									href='#allocations'
								>
									allocations
								</a>
								<a
									className='text-sm lg:text-base font-mono'
									href='#tokenomics'
								>
									tokenomics
								</a>
								<a
									className='text-sm lg:text-base font-mono'
									href='#night'
								>
									Night
								</a>
								<a
									className='text-sm lg:text-base font-mono'
									href='#dust'
								>
									dust
								</a>
								<a
									className='text-sm lg:text-base font-mono'
									href='#timeline'
								>
									timeline
								</a>
							</div>
						</div>
					</div>
				</nav>

				{/* Hero Section */}
				<section
					id='distribution'
					className='pt-32 pb-20 px-4 sm:px-6 lg:px-20 border-b-2'
				>
					<div className='flex  items-start  justify-between w-full'>
						<motion.div
							initial={{ opacity: 0, y: 20 }}
							animate={{ opacity: 1, y: 0 }}
							transition={{ duration: 0.8 }}
							className='flex flex-col-reverse lg:flex-row w-full items-center lg:items-start lg:justify-between  md:px-20'
						>
							<div className='space-y-6 lg:space-y-4 max-w-xl pt-10 lg:pt-48 flex flex-col items-center lg:items-start justify-center'>
								<p className='uppercase font-mono md:text-xl text-gray-700'>
									midnight token distribution
								</p>
								<h3 className='text-2xl md:text-5xl font-semibold'>
									Coming soon
								</h3>
								<p className='md:text-xl font-medium text-center lg:text-left'>
									The free, multi-phase distribution of NIGHT
									tokens is aimed at empowering a broad,
									diverse community to build the future of the
									Midnight network.
								</p>
								<div className='flex flex-col md:flex-row items-center gap-4'>
									<Button
										className='bg-[var(--primary-color)] uppercase text-white py-2 w-md h-12 px-10 hover:bg-blue-800 '
										onClick={() => {
											setOpen(true);
										}}
									>
										<Link href='/'>
											Read Tokenomics whitepaper
										</Link>
									</Button>
									<Button
										variant='outline'
										className=' uppercase py-2 w-md h-12 px-10 border-gray-700 w-md'
									>
										<Link href='/'>How to get night</Link>
									</Button>
								</div>
							</div>

							<motion.div
								whileHover={{ scale: 1.05 }}
								whileTap={{ scale: 0.95 }}
								className='  '
							>
								<Image
									src='/hero.svg'
									alt='hero'
									width={250}
									height={250}
									className='w-full h-full object-contain'
								/>
							</motion.div>
						</motion.div>
					</div>
				</section>

				{/* Features Section */}
				<section
					id='features'
					className='py-20 px-4 sm:px-10 lg:px-20'
				>
					<div className='max-w-7xl mx-auto'>
						<motion.div
							initial={{ opacity: 0, y: 20 }}
							whileInView={{ opacity: 1, y: 0 }}
							viewport={{ once: true }}
							className='text-center mb-16'
						>
							<h2 className='text-2xl md:text-4xl font-medium mb-6'>
								Multi-phase token distribution
							</h2>
							<p className='md:text-xl  max-w-2xl mx-auto'>
								NIGHT token allocations will be granted for free
								to eligible participants through a multi-phase
								token distribution: no purchase is involved.{' '}
								<br /> <br /> The distribution will consist
								primarily of three Claim phases and a Redemption
								period, giving a broad community of users
								multiple opportunities to participate.
							</p>
						</motion.div>

						<div className='grid lg:grid-cols-2  gap-8'>
							<div className='bg-purple-100/20 rounded-2xl p-10 flex flex-col items-center space-y-4'>
								<h3 className='text-2xl font-medium my-7'>
									Claims
								</h3>
								<Image
									src={'/claim.webp'}
									width={1000}
									height={1000}
									alt='claim'
									className='mt-4 h-full w-full '
								/>
								<p className='text-center text-xl text-gray-500 font-medium'>
									Participants claim their token allocations
									by demonstrating they meet the eligibility
									criteria for each phase.
								</p>
							</div>
							<div className='bg-purple-100/20 rounded-2xl p-10 flex flex-col items-center space-y-4'>
								<h3 className='text-2xl font-medium my-7'>
									Redemption
								</h3>
								<Image
									src={'/redem.webp'}
									width={1000}
									height={1000}
									alt='claim'
									className='mt-4 h-full w-full '
								/>
								<p className='text-center text-xl text-gray-500 font-medium'>
									Claimants then redeem their tokens as they
									thaw (unlock) during the Redemption period,
									thus transferring their tokens to their
									Destination Address.
								</p>
							</div>
						</div>
						<div className='flex items-center justify-center mt-10'>
							<Button
								className='bg-[var(--primary-color)] uppercase text-white py-2 w-md h-12 px-10 hover:bg-blue-800 '
								onClick={() => {
									setOpen(true);
								}}
							>
								How to claim
							</Button>
						</div>
					</div>
				</section>
				<section
					id='tokenomics'
					className='pb-28 border-b border-gray-200'
				>
					<div className='max-w-7xl mx-auto px-5 md:px-0'>
						<h2 className='text-2xl md:text-4xl font-semibold mb-6 text-center text-gray-00'>
							Token allocation
						</h2>
						<p className='md:text-xl text-gray-700 font-medium text-center max-w-2xl mx-auto'>
							The allocation of the NIGHT token supply will follow
							the three claim phases below. Community
							participation levels during each phase will
							determine allocations towards core network
							constituents.
						</p>
					</div>
					<div className='grid grid-cols-1  lg:grid-cols-2  gap-10 mt-16 max-w-[90rem] mx-auto bg-purple-100/20 rounded-2xl p-10 md:p-20 justify-center'>
						<Accordion
							type='single'
							collapsible
							className='w-full '
							defaultValue='item-1'
						>
							<AccordionItem value='item-1'>
								<AccordionTrigger className='text-xl md:text-2xl font-semibold'>
									Claim phase 1: Glacier Drop
								</AccordionTrigger>
								<AccordionContent className='flex flex-col gap-4 text-balance py-5'>
									<p className='text-lg md:text-xl text-gray-700 font-medium'>
										Our flagship product combines
										cutting-edge technology with sleek
										design. Built with premium materials, it
										offers unparalleled performance and
										reliability.
									</p>
									<ul className='space-y-3 text-base text-gray-700 font-medium list-disc list-inside '>
										<li>
											<span className='font-sans font-semibold'>
												50%{' '}
											</span>
											of the supply allocated to ADA
											holders
										</li>
										<li>
											<span className='font-sans font-semibold'>
												20%{' '}
											</span>
											of the supply allocated to Cardano
											community members
										</li>
										<li>
											<span className='font-sans font-semibold'>
												30%{' '}
											</span>
											split among holders of ETH, SOL,
											XRP, BNB, AVAX, and BAT, in
											proportion to their relative USD
											value
										</li>
									</ul>
								</AccordionContent>
							</AccordionItem>
							<AccordionItem value='item-2'>
								<AccordionTrigger className='text-xl md:text-2xl font-semibold'>
									Claim phase 2: Scavenger Mine
								</AccordionTrigger>
								<AccordionContent className='flex flex-col gap-4 text-balance py-5'>
									<p className='text-lg md:text-xl text-gray-700 font-medium'>
										During this phase, 100% of the unclaimed
										tokens from the Glacier Drop phase will
										be processed and apportioned between
										participants, core network constituents
										(Midnight Foundation, Midnight TGE,
										Reserve, and on-chain Treasury), and the
										third claim phase. For more details,
										check out the Midnight tokenomics and
										incentives whitepaper.
									</p>
								</AccordionContent>
							</AccordionItem>
							<AccordionItem value='item-3'>
								<AccordionTrigger className='text-xl md:text-2xl font-semibold'>
									Claim phase 3: Lost-and-Found
								</AccordionTrigger>
								<AccordionContent className='flex flex-col gap-4 text-balance py-5'>
									<p className='text-lg md:text-xl text-gray-700 font-medium'>
										The amount of tokens remaining on the
										Lost-and-Found pool will be claimable by
										those Glacier Drop-eligible individuals
										who missed the first claim phase as a
										fraction of their original entitlements.
									</p>
								</AccordionContent>
							</AccordionItem>
						</Accordion>
						<div className='flex items-center justify-center'>
							<Image
								src={'/logo.svg'}
								width={300}
								height={100}
								alt='claim'
								className='mt-4  '
							/>
						</div>
					</div>
				</section>
				<section
					id='allocations'
					className='grid lg:grid-cols-2 gap-10 mt-16 max-w-[90rem] mx-auto  p-10 md:p-20 justify-center items-center'
				>
					<Image
						src={'/logo1.svg'}
						width={300}
						height={100}
						alt='claim'
						className=' mx-auto lg:mx-0'
					/>
					<div className='space-y-4'>
						<h2 className='text-2xl md:text-4xl font-medium mb-6  text-gray-00 text-center lg:text-left'>
							Dual-component tokenomics
						</h2>
						<p className='text-lg md:text-xl text-gray-700 font-medium  max-w-2xl mx-auto text-center lg:text-left'>
							Midnight introduces a composite system where NIGHT,
							the native token, continually generates DUST, the
							shielded network resource that powers transactions.
							This segregation enables metadata protection and
							promotes sustainable operations.
							<br /> <br /> There’s no capital expenditure for
							executing transactions: NIGHT holders can
							effectively transact on Midnight for free for as
							long as they hold enough tokens to generate the
							minimum required DUST.
						</p>
						<div className='flex flex-col space-y-3 items-center lg:items-start mt-10 lg:mt-0'>
							<Button
								className='bg-[var(--primary-color)] uppercase text-white py-2 w-[350px] h-12 px-10 hover:bg-blue-800 mr-4'
								onClick={() => {
									setOpen(true);
								}}
							>
								read tokenomics whitepaper
							</Button>
							<Button
								variant='outline'
								className=' uppercase py-2 w-[250px] h-12 px-10 border-gray-700 font-medium'
							>
								<Link href='/'>read MICA whitepaper</Link>
							</Button>
						</div>
					</div>
				</section>

				<section
					id='night'
					className='space-y-20 '
				>
					<div className=' bg-black max-w-7xl mx-auto md:rounded-2xl md:p-12 py-12 '>
						<div className='grid lg:grid-cols-2 gap-10 items-center py-10 md:p-10 justify-center lg:justify-start'>
							<div className='space-y-4'>
								<h2 className='text-4xl font-semibold mb-6  text-white uppercase text-center lg:text-left'>
									Night
								</h2>
								<p className='text-gray-400 text-lg md:text-xl font-medium max-w-lg text-center lg:text-left'>
									NIGHT is the{' '}
									<span className='font-semibold text-white'>
										utility token
									</span>{' '}
									and the main component driving the Midnight
									economic system.
								</p>
								<h4 className='text-white text-xl font-semibold text-center lg:text-left'>
									NIGHT utility
								</h4>
								<ul className='space-y-2 text-gray-400 text-lg font-medium max-w-lg list-disc list-inside text-center lg:text-left'>
									<li>
										Generating DUST resources to power
										transactions.
									</li>
									<li>
										Promoting network security as block
										production rewards
									</li>
									<li>
										Enabling decentralized on-chain
										governance (expected)
									</li>
									<li>
										Driving ecosystem growth initiatives
										(expected)
									</li>
								</ul>
							</div>
							<div className='flex items-center justify-center w-full'>
								<Image
									src={'/logo2.svg'}
									width={300}
									height={100}
									alt='claim'
									className='  '
								/>
							</div>
						</div>
						<h2 className='text-xl  mb-6 mt-20  text-white text-center'>
							What is the NIGHT token?
						</h2>
						<div className='flex items-center justify-center mt-10'>
							<iframe
								width='560'
								height='315'
								src='https://www.youtube.com/embed/Nn39DYe1otU?si=Oz6CT1NoXhKA4sob'
								title='YouTube video player'
								frameBorder='0'
								allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share'
								referrerPolicy='strict-origin-when-cross-origin'
							></iframe>
						</div>
						<div className='mt-20 overflow-x-hidden'>
							<div className='mt-20 flex items-center  gap-x-10 overflow-x-scroll scrollbar-hide'>
								{features.map((feature, index) => (
									<div
										key={index}
										className='min-w-[400px] h-[500px] flex flex-col justify-between border border-gray-400 rounded-2xl p-10  bg-gray-200/10 '
									>
										<Image
											src={'/logo2.svg'}
											width={50}
											height={100}
											alt='claim'
											className='  '
										/>
										<div className='space-y-2 '>
											<h3 className='text-xl font-semibold text-white'>
												{feature.title}
											</h3>
											<p className='text-gray-400 text-lg font-medium'>
												{feature.description}
											</p>
										</div>
									</div>
								))}
							</div>
							<div className='flex items-center justify-center mt-10'>
								<Button
									className='bg-[var(--primary-color)] uppercase text-white py-2 w-md h-12 px-10 hover:bg-blue-800 '
									onClick={() => {
										setOpen(true);
									}}
								>
									Read whitepaper
								</Button>
							</div>
						</div>
					</div>
					<div
						id='dust'
						className='bg-gray-200/30 rounded-2xl p-12 max-w-7xl mx-auto border border-gray-400'
					>
						<div className='grid grid-cols-1 lg:grid-cols-2 gap-10 items-center p-10'>
							<div className='space-y-4'>
								<h3 className='text-4xl font-semibold mb-6  text-gray-00 text-center lg:text-left'>
									DUST
								</h3>
								<p className='text-gray-600 text-lg font-medium max-w-[28rem] mx-auto lg:mx-0 text-center lg:text-left'>
									DUST is the shielded and renewable{' '}
									<span className='font-semibold text-black'>
										network resource
									</span>{' '}
									whose single function is to allow users to
									execute transactions on Midnight.
								</p>
							</div>
							<div className='flex items-center justify-center w-full'>
								<Image
									src={'/dust.svg'}
									width={300}
									height={100}
									alt='claim'
									className='  '
								/>
							</div>
						</div>
						<div className='mt-20 overflow-x-hidden'>
							<div className='mt-20 flex items-center  gap-x-10 overflow-x-scroll scrollbar-hide'>
								{features2.map((feature, index) => (
									<div
										key={index}
										className='min-w-[400px] h-[500px] flex flex-col justify-between border border-gray-400 rounded-2xl p-10  bg-gray-200/10 '
									>
										<Image
											src={'/dust1.svg'}
											width={50}
											height={100}
											alt='claim'
											className='  '
										/>
										<div className='space-y-2 '>
											<h3 className='text-xl font-semibold text-gray-800'>
												{feature.title}
											</h3>
											<p className='text-gray-600 text-lg font-medium'>
												{feature.description}
											</p>
										</div>
									</div>
								))}
							</div>
							<div className='flex items-center justify-center mt-10'>
								<Button
									className='bg-[var(--primary-color)] uppercase text-white py-2 w-md h-12 px-10 hover:bg-blue-800 '
									onClick={() => {
										setOpen(true);
									}}
								>
									Read whitepaper
								</Button>
							</div>
						</div>
					</div>
				</section>
				<section
					id='timeline'
					className='bg-gray-200/40  md:rounded-2xl  md:p-12  mt-20'
				>
					<div className='grid grid-cols-1 lg:grid-cols-2 gap-10 items-start p-5 py-10 md:p-10'>
						<h3 className='text-4xl md:text-5xl font-semibold text-center md:text-left  text-gray-800'>
							Timeline
						</h3>
						<div>
							<Accordion
								type='single'
								collapsible
								className='w-full space-y-4'
							>
								<AccordionItem
									value='item-1'
									className='border-none'
								>
									<AccordionTrigger className=' flex items-center gap-2  bg-white  rounded-t-2xl p-6 py-7'>
										<div className='space-y-2'>
											<p className='text-gray-700 font-medium '>
												Claim phase 1: Glacier Drop
											</p>
											<h3 className='text-2xl font-medium text-gray-800'>
												Glacier Drop
											</h3>
											<p className='text-gray-700 font-medium'>
												Duration: 60 days
											</p>
										</div>
									</AccordionTrigger>
									<AccordionContent className='flex flex-col gap-4 text-balance py-5 bg-white rounded-b-2xl p-10 border-t border-gray-400'>
										<p className='text-lg text-gray-700 font-medium'>
											An evolution of the traditional
											airdrop formula, where tokens are
											merely dropped into eligible users’
											wallets, the Glacier Drop includes
											mechanisms to increase its fairness,
											integrity, and resistance to being
											exploited by malicious parties –
											including the gradual thawing
											(unlocking) of claims, which
											inspires the Glacier part of its
											name. <br /> <br /> Claimants
											holding a minimum balance equivalent
											to $100 in one or more eligible
											tokens (ADA, BTC, ETH, SOL, XRP,
											BNB, AVAX, or BAT) in their native
											blockchains – based on a random
											historical snapshot of each – are
											eligible to participate. Individual
											allocations are calculated based on
											their holdings and on the share of
											the supply apportioned to each
											network. <br /> <br />
											Successful claims are subject to
											thawing during the Redemption
											period. Unclaimed tokens carry over
											to the next phase.
										</p>
										<Link
											href=''
											className='text-blue-700 font-medium text-2xl underline mt-10'
										>
											How to claim
										</Link>
									</AccordionContent>
								</AccordionItem>
								<AccordionItem
									value='item-2'
									className='border-none'
								>
									<AccordionTrigger className=' flex items-center gap-2  bg-white  rounded-t-2xl p-6 py-7'>
										<div className='space-y-2'>
											<p className='text-gray-700 font-medium '>
												Claim phase 2
											</p>
											<h3 className='text-2xl font-medium text-gray-800'>
												Scavenger Mine
											</h3>
											<p className='text-gray-700 font-medium'>
												Duration: 30 days
											</p>
										</div>
									</AccordionTrigger>
									<AccordionContent className='flex flex-col gap-4 text-balance py-5 bg-white rounded-b-2xl p-10 border-t border-gray-400 space-y-4'>
										<p className='text-lg text-gray-700 font-medium'>
											Scavenger Mine expands eligibility
											requirements and allows anyone to
											claim a share of unclaimed tokens
											from the previous phase by solving
											computational tasks. Successful
											claimants will be rewarded with
											NIGHT tokens in proportion to the
											computational efforts they put in.
											During Scavenger Mine, all tokens
											that were left unclaimed during
											Glacier Drop will be processed and
											apportioned.
										</p>
										<ul className='space-y-2 text-gray-700 font-medium text-lg list-disc list-inside'>
											<li>
												A share of the tokens will be
												allocated for claiming by
												Scavenger Mine participants.
												This share will be determined
												based on the result of Glacier
												Drop.
											</li>
											<li>
												The remaining tokens will be
												apportioned to the core network
												constituents – Reserve,
												Treasury, Midnight Foundation,
												and Midnight TGE (the token
												issuer) – and to the third claim
												phase, as detailed in the
												whitepaper.
											</li>
										</ul>
										<p className='text-gray-700 font-medium text-lg'>
											Successful claims are subject to
											thawing during the Redemption
											period. More details on eligibility
											requirements and how to participate
											will be published at a later date.
										</p>
									</AccordionContent>
								</AccordionItem>
								<AccordionItem
									value='item-3'
									className='border-none'
								>
									<AccordionTrigger className=' flex items-center gap-2  bg-white  rounded-t-2xl p-6 py-7'>
										<div className='space-y-2'>
											<h3 className='text-2xl font-medium text-gray-800'>
												Thawing & Redemption period
											</h3>
											<p className='text-gray-700 font-medium'>
												Duration: 450 days
											</p>
										</div>
									</AccordionTrigger>
									<AccordionContent className='flex flex-col gap-4 text-balance py-5 bg-white rounded-b-2xl p-10 border-t border-gray-400 space-y-4'>
										<p className='text-lg text-gray-700 font-medium'>
											During the Redemption period,
											Glacier Drop and Scavenger Mine
											claims thaw (unlock) following a
											staggered schedule in four
											installments over the course of 360
											days. The date of a claimed
											allocation’s first installment is
											randomly determined to fall over a
											range of 1-90 days), with subsequent
											installments following every 90
											days. Allocation thaws happen in
											equal 25% shares. <br /> <br />{' '}
											Claimants may choose to redeem each
											share of their allotted tokens as
											they thaw, or wait until they fully
											unlock to redeem the whole allotment
											at once. Each redemption involves a
											Cardano transaction, thus requiring
											claimants to cover the cost of the
											Cardano network transaction fee.{' '}
											<br /> <br /> The Redemption period
											concludes with a 90- day grace
											period during which the NIGHT Claim
											Portal website will remain
											operational, allowing redemptions to
											continue beyond the thawing of the
											last tokens.
										</p>
										<Link
											href='https://www.midnight.gd/how-to-get-night'
											className='text-blue-700 font-medium text-2xl underline mt-10'
										>
											How to redeem
										</Link>
									</AccordionContent>
								</AccordionItem>
								<AccordionItem
									value='item-4'
									className='border-none'
								>
									<AccordionTrigger className=' flex items-center gap-2  bg-white  rounded-t-2xl p-6 py-7'>
										<div className='space-y-2'>
											<p className='text-gray-700 font-medium '>
												Claim phase 3
											</p>
											<h3 className='text-2xl font-medium text-gray-800'>
												Lost-and-found
											</h3>
											<p className='text-gray-700 font-medium text-lg'>
												Duration: 4 years
											</p>
										</div>
									</AccordionTrigger>
									<AccordionContent className='flex flex-col gap-4 text-balance py-5 bg-white rounded-b-2xl p-10 border-t border-gray-400 space-y-4'>
										<p className='text-lg text-gray-700 font-medium'>
											The Lost-and-Found phase will begin
											sometime after the Midnight mainnet
											launches, giving original Glacier
											Drop-eligible participants (who did
											not claim during the initial 60-day
											claim period) another chance to
											claim a fraction of their original
											allocations.
											<br /> <br />
											Participants claiming during this
											phase will have to use their own
											means to interact with the Midnight
											network smart contract that will
											hold their allocated tokens, and to
											submit and process their claims.
											Unclaimed tokens after the four-year
											period will be reallocated to the
											on-chain Treasury. <br /> <br />
											More information about this phase
											will be published at a later date.
										</p>
									</AccordionContent>
								</AccordionItem>
								<AccordionItem
									value='item-5'
									className='border-none'
								>
									<AccordionTrigger className=' flex items-center gap-2  bg-white  rounded-t-2xl p-6 py-14'>
										<div className='space-y-2'>
											<h3 className='text-2xl font-medium text-gray-800'>
												NIGHT claim portal sunsetting
											</h3>
										</div>
									</AccordionTrigger>
									<AccordionContent className='flex flex-col gap-4 text-balance py-5 bg-white rounded-b-2xl p-10 border-t border-gray-400 space-y-4'>
										<p className='text-lg text-gray-700 font-medium'>
											Following the Redemption period
											90-day grace period, the NIGHT Claim
											Portal will cease to be operational,
											and participants in Glacier Drop and
											Scavenger Mine who have not yet
											redeemed their tokens will have to
											use their own means to interact with
											the smart contracts on the Cardano
											network to do so.
										</p>
									</AccordionContent>
								</AccordionItem>
							</Accordion>
						</div>
					</div>
				</section>
				{/* Footer */}
				<footer className='px-5 p-12  md:px-20  border-t border-midnight-800 bg-[var(--primary-color)] space-y-12'>
					<div>
						<h1 className='text-white text-4xl font-bold'>
							midnight
						</h1>
					</div>
					<div className='grid md:grid-cols-2 lg:grid-cols-3 gap-10 text-white  pb-10'>
						<div className='lg:col-span-2 grid grid-cols-1 lg:grid-cols-2 gap-5'>
							<div className='space-y-4'>
								<h3 className='uppercase text-xl font-mono '>
									Explore
								</h3>
								<div className='space-y-2 flex flex-col'>
									<a
										className='hover:text-gray-400 text-xl font-medium'
										href=''
									>
										midnight.network
									</a>
									<a
										className='hover:text-gray-400 text-xl font-medium'
										href=''
									>
										midnight.foundation
									</a>
									<a
										className='hover:text-gray-400 text-xl font-medium'
										href=''
									>
										docs.midnight.network
									</a>
								</div>
							</div>
							<div className='space-y-4'>
								<h3 className='uppercase text-xl font-mono '>
									whitepaper
								</h3>
								<div className='space-y-2 flex flex-col'>
									<a
										className='hover:text-gray-400 text-xl font-medium'
										href=''
									>
										MiCA
									</a>
									<a
										className='hover:text-gray-400 text-xl font-medium'
										href=''
									>
										Tokenomics
									</a>
								</div>
							</div>
						</div>
						<div className='space-y-4'>
							<h3 className='uppercase text-xl font-mono '>
								sign up for updates
							</h3>
							<div className='space-y-3 flex flex-col'>
								<label
									htmlFor='email'
									className='text-xl font-medium'
								>
									Email{' '}
									<span className='text-red-500'>*</span>
								</label>
								<input
									type='text'
									placeholder='subscribe to our newsletter'
									className='w-full p-2 px-6 rounded-md h-16 bg-transparent border-2 border-white'
								/>
								<div className='flex items-start gap-x-4'>
									<input
										type='checkbox'
										id='terms'
									/>
									<label
										htmlFor='terms'
										className='text-sm font-medium'
									>
										By checking this box, I agree to allow
										Midnight TGE to store and process the
										personal data submitted on this form in
										accordance with the Midnght TGE Privacy
										Policy . Note: emails will come from
										info@midnighttge.io for whitelisting
										purposes.*
									</label>
								</div>
								<button className='text-xl font-medium text-white bg-black px-4 py-3 rounded-md max-w-[120px]'>
									Submit
								</button>
							</div>
						</div>
					</div>
					<div className='space-y-6 border-t border-gray-800 w-full pt-10 '>
						<h4 className='text-lg text-white uppercase'>
							Follow midnight
						</h4>
						<div className='flex flex-col lg:flex-row lg:items-center gap-y-4 lg:gap-x-8'>
							<a
								href=''
								className='flex items-center gap-x-2 text-xl font-mono text-white'
							>
								<FaXTwitter />
								Twitter
							</a>
							<a
								href=''
								className='flex items-center gap-x-2 text-xl font-mono text-white'
							>
								<FaTelegram />
								Telegram
							</a>
							<a
								href=''
								className='flex items-center gap-x-2 text-xl font-mono text-white'
							>
								<FaDiscord />
								Discord
							</a>
							<a
								href=''
								className='flex items-center gap-x-2 text-xl font-mono text-white'
							>
								<FaYoutube />
								Youtube
							</a>
							<a
								href=''
								className='flex items-center gap-x-2 text-xl font-mono text-white'
							>
								<FaLinkedin />
								Linkedin
							</a>
						</div>
					</div>
				</footer>
				<div className='text-white  py-4 bg-[var(--primary-color)] border-t border-gray-800 px-5 md:px-20 flex flex-col md:flex-row md:items-center  gap-5 md:gap-10 uppercase font-[400]'>
					<a
						href=''
						className='text-sm md:text-base font-mono'
					>
						Privacy Policy
					</a>

					<a
						href=''
						className='text-sm md:text-base font-mono'
					>
						Terms & Conditions
					</a>
					<a
						href=''
						className='text-sm md:text-base font-mono'
					>
						Cookie Policy
					</a>
				</div>
			</div>
		</>
	);
}
